[wokwi]
version = 1
firmware = "../../../.pio/build/esp32-s3-devkitc-1/firmware.bin"
elf = "../../../.pio/build/esp32-s3-devkitc-1/firmware.elf"

# RFC2217 虚拟串口
rfc2217ServerPort = 4000

# 私有网关
[net]
gateway = "ws://localhost:9011"
